name: shop
description: null

publish_to: "none"

version: 17.0.0+22

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10+1
  form_field_validator: ^1.1.0
  cached_network_image: ^3.2.0
  flutter_rating_bar: ^4.0.1
  flutter_widget_from_html_core: ^0.15.1
  animations: ^2.0.11
  url_launcher: ^6.3.1
  url_launcher_ios: ^6.3.1
  dartz: ^0.10.1
  dio: ^5.3.2
  equatable: ^2.0.5
  flutter_secure_storage: ^9.2.2
  flutter_staggered_animations: ^1.1.1
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.0
  logger: ^2.4.0
  flutter_riverpod: ^2.3.7
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.1.2

  get_it: ^8.0.0
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  shimmer: ^3.0.0
  file_picker: ^8.1.7
  image_picker: ^1.1.2
  easy_date_timeline: ^2.0.6
  week_day_picker: ^1.1.3
  liquid_pull_to_refresh: ^3.0.1
  webview_flutter: ^4.13.0
  flutter_paytabs_bridge: ^2.7.1
  easy_stepper: ^0.8.5+1
  # http: ^1.2.2 # No longer needed for PayTabs SDK
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.3.3
  riverpod_generator: ^2.2.4

  freezed: ^2.4.1
  json_serializable: ^6.6.2

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/Illustration/
    - assets/flags/
    - assets/logo/
    - assets/screens/

  fonts:
    - family: Plus Jakarta
      fonts:
        - asset: assets/fonts/plus_jakarta/PlusJakartaDisplay-Regular.otf
        - asset: assets/fonts/plus_jakarta/PlusJakartaDisplay-Medium.otf
          weight: 500
        - asset: assets/fonts/plus_jakarta/PlusJakartaDisplay-Bold.otf
          weight: 700
    - family: Grandis Extended
      fonts:
        - asset: assets/fonts/grandis_extended/GrandisExtended-Regular.ttf
        - asset: assets/fonts/grandis_extended/GrandisExtended-Thin.ttf
          weight: 300
        - asset: assets/fonts/grandis_extended/GrandisExtended-Medium.ttf
          weight: 500
        - asset: assets/fonts/grandis_extended/GrandisExtended-Bold.ttf
          weight: 700
        - asset: assets/fonts/grandis_extended/GrandisExtended-Black.ttf
          weight: 900
flutter_intl:
  enabled: true
